import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const fira = Fira_Code({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Relix",
  description: "Generated by create next app",
  icons: {
    icon: "../assets/tech-guy.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fira.className}>
        <div className="relative w-full flex items-center justify-center bg-[#0A1415] flex-col">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
